//Indian FDI Equity Inflow: Top 10 Countries
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;Top10countriesFDIEquityIndia&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="Top10countriesFDIEquityIndia/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/To/Top10countriesFDIEquityIndia/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

// India FDI Equity Inflow: Top 10 Sectors
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;FD&#47;FDIEquityInflowIndiaTop10Sectors-PieChart&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="600"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="FDIEquityInflowIndiaTop10Sectors-PieChart/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/FD/FDIEquityInflowIndiaTop10Sectors-PieChart/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Indian FDI Equity Inflow: Top 10 Regional Offices

	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndianFDIEquityInflowTop10RegionalOffices&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="IndianFDIEquityInflowTop10RegionalOffices/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/In/IndianFDIEquityInflowTop10RegionalOffices/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Indo-Canadian Companies: Industry Based Percentages
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;Indo-CanadianCompanies-SectorWise&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="Indo-CanadianCompanies-SectorWise/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/In/Indo-CanadianCompanies-SectorWise/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Canadian Companies in India
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;St&#47;StatewiseIndiaMapforCanadiancompanies_0&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="StatewiseIndiaMapforCanadiancompanies_0/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/St/StatewiseIndiaMapforCanadiancompanies_0/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Indian Companies in Canada 
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript>&lt;a href='#'&gt;&lt;img alt='Sheet 1 ' src='https:&amp;#47;&amp;#47;public.tableau.com&amp;#47;static&amp;#47;images&amp;#47;PQ&amp;#47;PQRH3XCBN&amp;#47;1_rss.png' style='border: none' /&gt;&lt;/a&gt;</noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="path" value="shared/PQRH3XCBN" /> <param name="toolbar" value="yes" /><param name="static_image" value="https://public.tableau.com/static/images/PQ/PQRH3XCBN/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>
	
//FDI Stock: India-Canada Bilateral Trade
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;FD&#47;FDIStockIndia-Canada2001-2014&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="FDIStockIndia-Canada2001-2014/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/FD/FDIStockIndia-Canada2001-2014/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Indo-Canadian Relation: Import/Export
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Im&#47;ImportExportIndo-CanadianTrade&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="ImportExportIndo-CanadianTrade/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/Im/ImportExportIndo-CanadianTrade/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Total FDI India: Inflows during 2005-2015
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;TotalFDIFlowingintoIndia-2005-2015&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="TotalFDIFlowingintoIndia-2005-2015/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/To/TotalFDIFlowingintoIndia-2005-2015/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Factors Affecting Business: India and Canada
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Fa&#47;FactorsAffectingBusiness-IndiaandCanada&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="FactorsAffectingBusiness-IndiaandCanada/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/Fa/FactorsAffectingBusiness-IndiaandCanada/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Top 10 Canadian Goods Exported to India
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script></p>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;Top10CandianGoodsExportedfromIndia-2014&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="Top10CandianGoodsExportedfromIndia-2014/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/To/Top10CandianGoodsExportedfromIndia-2014/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//Top 10 Canadian Good Imported from India
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;To&#47;Top10CanadianGoodsImportedfromIndia&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="Top10CanadianGoodsImportedfromIndia/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/To/Top10CanadianGoodsImportedfromIndia/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showVizHome" value="no" /><param name="showTabs" value="y" /><param name="bootstrapWhenNotified" value="true" /></object></div>

//India and Canada: GDP Growth Rate
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script></p>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px; text-align: justify;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaGDPperCapitaGrowthRateAnnual&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="IndiaandCanadaGDPperCapitaGrowthRateAnnual/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/In/IndiaandCanadaGDPperCapitaGrowthRateAnnual/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showTabs" value="y" /></object></div>

//India and Canada: Tax Revenue % of GDP
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script></p>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px; text-align: justify;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaTaxRevenueasaPercentageofGDP&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="IndiaandCanadaTaxRevenueasaPercentageofGDP/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/In/IndiaandCanadaTaxRevenueasaPercentageofGDP/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showTabs" value="y" /></object></div>

//India and Canada: Time Required to Start Business
	<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script>
	<div class='tableauPlaceholder' style='width: 982px; height: 742px;'><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaTimeRequiredtostartabusiness&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='982' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='IndiaandCanadaTimeRequiredtostartabusiness&#47;Sheet1' /><param name='tabs' value='no' /><param name='toolbar' value='no' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaTimeRequiredtostartabusiness&#47;Sheet1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showTabs' value='y' /></object></div>

//India and Canada: External Debt Stocks
	<script src="https://public.tableau.com/javascripts/api/viz_v1.js" type="text/javascript"></script></p>
	<div class="tableauPlaceholder" style="width: 982px; height: 742px; text-align: justify;"><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaExternalDebtStocks2008to2013&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class="tableauViz" style="display: none;" width="982" height="742"><param name="host_url" value="https%3A%2F%2Fpublic.tableau.com%2F" /> <param name="site_root" value="" /><param name="name" value="IndiaandCanadaExternalDebtStocks2008to2013/Sheet1" /><param name="tabs" value="no" /><param name="toolbar" value="no" /><param name="static_image" value="https://public.tableau.com/static/images/In/IndiaandCanadaExternalDebtStocks2008to2013/Sheet1/1.png" /> <param name="animate_transition" value="yes" /><param name="display_static_image" value="yes" /><param name="display_spinner" value="yes" /><param name="display_overlay" value="yes" /><param name="display_count" value="yes" /><param name="showTabs" value="y" /></object></div>

//INR vs. CAD: Aug 2015 - March 2016
	<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script>
	<div class='tableauPlaceholder' style='width: 982px; height: 742px;'><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndianRupeewithrespecttoCanadianDollar15thAugust2015to24thMarch2016&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='982' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='IndianRupeewithrespecttoCanadianDollar15thAugust2015to24thMarch2016&#47;Sheet1' /><param name='tabs' value='no' /><param name='toolbar' value='no' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndianRupeewithrespecttoCanadianDollar15thAugust2015to24thMarch2016&#47;Sheet1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showTabs' value='y' /></object></div>

//India and Canada: Internet and Mobile Users
	<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script>
	<div class='tableauPlaceholder' style='width: 982px; height: 742px;'><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;37&#47;37YBBXZZH&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='982' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='path' value='shared&#47;37YBBXZZH' /> <param name='toolbar' value='no' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;37&#47;37YBBXZZH&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showTabs' value='y' /></object></div>

//India and Canada: High Technology Exports
	<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script>
	<div class='tableauPlaceholder' style='width: 982px; height: 742px;'><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;XF&#47;XFD6428X3&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='982' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='path' value='shared&#47;XFD6428X3' /> <param name='toolbar' value='no' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;XF&#47;XFD6428X3&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showTabs' value='y' /></object></div>

//India and Canada: Inflation (GDP Deflator)
	<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script>
	<div class='tableauPlaceholder' style='width: 982px; height: 742px;'><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaInflationGDPDeflatorannual&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='982' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='IndiaandCanadaInflationGDPDeflatorannual&#47;Sheet1' /><param name='tabs' value='no' /><param name='toolbar' value='no' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;In&#47;IndiaandCanadaInflationGDPDeflatorannual&#47;Sheet1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showTabs' value='y' /></object></div>

//India and Canada: Military Expenditure
	<script type='text/javascript' src='https://public.tableau.com/javascripts/api/viz_v1.js'></script>
	<div class='tableauPlaceholder' style='width: 982px; height: 742px;'><noscript><a href='#'><img alt='Sheet 1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;mi&#47;militaryexpenditureasapercentageofgdp&#47;Sheet1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' width='982' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='militaryexpenditureasapercentageofgdp&#47;Sheet1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;mi&#47;militaryexpenditureasapercentageofgdp&#47;Sheet1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showTabs' value='y' /></object></div>









